controller_manager:
  ros__parameters:
    update_rate: 30
    #use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['front_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint']
    wheel_separation: 0.50
    wheel_radius: 0.10115

    use_stamped_vel: false

    open_loop: true    

    #wheels_per_side: 1
    #wheel_separation_multiplier: 1.0
    #left_wheel_radius_multiplier: 1.0
    #right_wheel_radius_multiplier: 1.0
  
    odom_frame_id: odom
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    #enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    #linear.x.has_velocity_limits: true
    #linear.x.has_acceleration_limits: true
    #linear.x.has_jerk_limits: false
    linear.x.max_velocity: 25.0
    linear.x.min_velocity: -25.0
    #linear.x.max_acceleration: 1.0
    #linear.x.max_jerk: 0.0
    #linear.x.min_jerk: 0.0
    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    angular.z.max_velocity: 10.0
    angular.z.min_velocity: -10.0
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters:
